### ISSUE TITLE
Add context menu actions for individual games

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi-playnite#1]
This is dependent on https://github.com/JosefNemec/Playnite/issues/524 making its way into a Playnite release. This would allow for an action to back up a specific game on demand.

**Comment by darklinkpower** [comment]
I also would add that it would be great to have an action to open the save directories in the same Ludusavi submenu.

**Comment by darklinkpower** [comment]
Documentation is already out in case you want to check it.

https://playnite.link/docs/playnite8/tutorials/menus.html?tabs=csharp

**Comment by mtkennerly** [comment]
This is now available in v0.4.0 🎉 

@darklinkpower I didn't (yet) add an option to open the individual game's save folder. There's not currently a way for the plugin to ask Ludusavi for that info, so I'll need to design that support first.
