### ISSUE TITLE
Add an option to disable the notification

### ISSUE THREAD

**Issue by burnpsy** [mtkennerly/ludusavi-playnite#10]
This is pretty much my only complaint with this plugin. I would rather not see a notification if it's just working normally, so I would like an option to turn off the notifications that just say the data was backed up.

**Comment by mtkennerly** [comment]
Thanks for the suggestion! I agree that would be a good option to add.

**Comment by mtkennerly** [comment]
This is now available in [v0.3.0](https://github.com/mtkennerly/ludusavi-playnite/releases/tag/v0.3.0).
