### ISSUE TITLE
Add a whitelist option/tag

### ISSUE THREAD

**Issue by lmgarret** [mtkennerly/ludusavi-playnite#14]
Hey ! First of all, thanks for the great job!
I have a suggestion which would be the exact opposite of https://github.com/mtkennerly/ludusavi-playnite/issues/9: could you add support for a tag (e.g. `ludusavi-backup`) and an option so that only games with this tag are backed up?

I'm in a situation whre for 100 games in my library, maybe only ~5 would require a back-up. The slight difference with not tagging these with `ludusavi-skip` is that you don't have to tag all of your other games with `ludusavi-skip` to only have these few backed up.

Also, as there is no 'default' tag mechanism in playnite, every new game will be backed up, when I'd prefer the inverse: manually choosing the few games to backup.

Let me know what you think :)

**Comment by mtkennerly** [comment]
Sounds like a good idea to me :+1:
