### ISSUE TITLE
Problems with games that store saves in the installation path

### ISSUE THREAD

**Issue by ferrazpedro** [mtkennerly/ludusavi-playnite#16]
Good evening!

I'm having some problems trying to backup saves from games that keeps saves in the installation directory (like Mighty No. 9). I keep my games in a folder in another HD, so maybe this is related.

Edit: Btw, I need to say that Ludusavi is amazing! It has really streamlined the process to backup all my saves, so thanks a lot!

**Comment by mtkennerly** [comment]
Hi! What roots do you have configured in Ludusavi? It sounds like you may need to add an `other`-type root pointing to the parent folder (e.g., if you have `D:\Games\Mighty No. 9`, then the root would point to `D:\Games`).

And thanks! I'm glad you like it \:D

**Comment by ferrazpedro** [comment]
That really solved it! Thanks a lot!
