### ISSUE TITLE
Issues with full screen mode

### ISSUE THREAD

**Issue by zany130** [mtkennerly/ludusavi-playnite#17]
This seems to be more of an issue with playnite than any extension (see here https://github.com/JosefNemec/Playnite/issues/2342), but I thought I should let you know that the pop-up that appears after closing a game doesn't  scale correctly in full-screen mode

![120146436-14f77300-c1b3-11eb-9c2a-5a845b117486](https://user-images.githubusercontent.com/25832539/121394510-688a5f00-c91f-11eb-9b05-78486331827e.png)
![120146359-f3968700-c1b2-11eb-9acc-4242ba470bd4](https://user-images.githubusercontent.com/25832539/121394514-6922f580-c91f-11eb-81b8-68eb12ba51c0.png)

**Comment by mtkennerly** [comment]
Thanks for bringing this up :+1: I know at least one other person who ran into it, but I couldn't figure out what was going on at the time, so I'm glad you were able to pinpoint some more detail about it.

**Comment by zany130** [comment]
Fixed in latest playnite update
