### ISSUE TITLE
Add support to run a script before backup

### ISSUE THREAD

**Issue by turtleship69** [mtkennerly/ludusavi-playnite#18]
Add support to run a script before backup, either globally as in for all games or per game, for example `rclone mount driveName`, or `7z a -tzip yourfile.zip yourfolder`.

**Comment by mtkennerly** [comment]
I think this should be added to Ludusavi itself instead of just the Playnite extension, so I've opened a ticket over there: https://github.com/mtkennerly/ludusavi/issues/98
