### ISSUE TITLE
No save data found to back upfor The Elder Scrolls V: SkyrimSpecial Edition   

### ISSUE THREAD

**Issue by sunencheng** [mtkennerly/ludusavi-playnite#23]
No save data found to back upfor The Elder Scrolls V: Skyrim Special Edition
I have installed 73 mods for skyrim.Now ,it can not backup skyrim's saves.Got this error.
Tanks.

**Comment by mtkennerly** [comment]
* Have you opened Ludusavi and configured the roots? If so, could you share your configuration?
* Where is the game installed?

**Comment by sunencheng** [comment]
> * Have you opened Ludusavi and configured the roots? If so, could you share your configuration?
> * Where is the game installed?

I only set configuration in playnite.This is my playnite setting:
![image](https://user-images.githubusercontent.com/8297524/140268424-9eae56f7-ccac-461e-8e67-cc6e58038e73.png)
The game installed "E:\steamGame\steamapps\common\Skyrim Special Edition".

**Comment by mtkennerly** [comment]
As noted in [the instructions](https://github.com/mtkennerly/ludusavi-playnite/blob/master/README.md#Configuration), you'll need to open Ludusavi and configure a root. In this case, you need a Steam root pointing to `E:\steamGame`. You can launch it directly from Playnite as well:

> ![image](https://user-images.githubusercontent.com/4934192/140784515-709a38ba-9106-44fa-84bd-be9f7d599c92.png)
