### ISSUE TITLE
Extension can't backup savedata of game "Overboard!"

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#29]
Ludusavi application detects save files correctly but the extension fails to detect the save files.

![image](https://user-images.githubusercontent.com/1389286/148620593-d96a9244-fc70-4f09-913d-de02ce1be92c.png)

Extensions.log

```
07-01 17:31:51.102|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --merge --try-update --path "C:\Users\Brandon\MEGAsync\OneDrive\Backups\saves\PC" "Overboard!" --api
07-01 17:31:52.694|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content
07-01 17:36:54.591|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --merge --try-update --path "C:\Users\Brandon\MEGAsync\OneDrive\Backups\saves\PC" "Overboard!" --api
07-01 17:36:56.049|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content
```

**Comment by mtkennerly** [comment]
It looks like the name is mismatched. It's called `Overboard! (2021)` in the manifest because of the PCGW title:

* https://www.pcgamingwiki.com/wiki/Overboard!_(2021)
* https://www.pcgamingwiki.com/wiki/Overboard!

You could rename it in Playnite to match the  manifest, or you could use the edit icon in Ludusavi to make a custom entry for `Overboard! (2021)` and rename the custom entry to match Playnite.

**Comment by darklinkpower** [comment]
Oh that explains it, thanks!. I always wondered how the game matched the save data.

I think an idea would be to save stores ids (steam Id, gog id, etc) in the Ludusavi manifest and try to match by store and id first so this way there wouldn't be mistmaches even if the name is different, then fallback to using the name if nothing is found. But this means a lot of work on Ludusavi, Ludusavi manifest and finally the extension so I don't know if it's worth it.

**Comment by mtkennerly** [comment]
Yeah, I agree something like that would be good. I created this ticket to track the idea: https://github.com/mtkennerly/ludusavi/issues/86
