### ISSUE TITLE
Unable to run Ludusavi

### ISSUE THREAD

**Issue by key34** [mtkennerly/ludusavi-playnite#33]
![Screenshot_2](https://user-images.githubusercontent.com/105783277/169008767-dad0b99c-fb76-4905-9681-71b6365e85d3.png)

Can you help me??

**Comment by mtkennerly** [comment]
In addition to the Playnite extension, have you also installed Ludusavi itself? If you don't have it, you can download it here: https://github.com/mtkennerly/ludusavi/releases (you'll probably want the latest 64-bit Windows version: https://github.com/mtkennerly/ludusavi/releases/download/v0.10.0/ludusavi-v0.10.0-win64.zip)

In the plugin settings, you'll just need to set the path to your ludusavi.exe, which you can extract from the ZIP file above. For example:

> ![image](https://user-images.githubusercontent.com/4934192/169011031-eb4d4c85-655d-4562-8aec-aefd8e61a294.png)
