### ISSUE TITLE
Add localizations support

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#34]
If I'm not wrong the extension has its own system for localization, but as a suggestion I would recommend to use the builtin system for extensions in Playnite:

Documentations: https://playnite.link/docs/master/tutorials/extensions/localizations.html?tabs=csharp

This way you can use something like [Crowdin](https://crowdin.com/) to provide an easy way to edit and update them and also have the string available in the plugin code and in xaml views and resources

An example of a configuration file for Crowdin to automatically pick localization files: https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/crowdin.yml

**Comment by mtkennerly** [comment]
I have some concerns with the builtin system that have kept me from using it:

* String ID-based translations generally constrain the target language to the source language's grammar. For example, you might have `FriendOwnsOneGame` and `FriendOwnsMultipleGames` IDs, which doesn't make sense for a language without the singular/plural distinction (Japanese) and is insufficient for a language with an additional dual distinction (Arabic).
* String IDs must be globally unique across extensions.
* String IDs must be duplicated in each language's file, which is prone to typos and copy/paste errors.

Something like [Project Fluent](https://projectfluent.org/) solves the first issue, although it still has the third issue.

**Comment by mtkennerly** [comment]
Oh, it looks like Crowdin actually supports Project Fluent ([source](https://support.crowdin.com/supported-formats/)), and there are a couple of .NET implementations ([Fluent.Net](https://github.com/blushingpenguin/Fluent.Net), [Linguini](https://github.com/Ygg01/Linguini)). I'll give it a shot, since it addresses two of my three concerns.

**Comment by mtkennerly** [comment]
Both Ludusavi and the plugin are now on Crowdin and using Project Fluent for translation files:

* Ludusavi: https://crowdin.com/project/ludusavi
* Plugin: https://crowdin.com/project/ludusavi-playnite

I'll try to get a plugin release out within the next few days with the latest changes.
