### ISSUE TITLE
Ludusavi creates backup of Documents folder called "The Lord of the Rings: The Return of the King"

### ISSUE THREAD

**Issue by aplatero29** [mtkennerly/ludusavi-playnite#36]
Hi there, I've been checking out this plugin for a while now and I came across something that doesn't make sense.

I selected the *Back up save data for all games* option through Playnite and in the report the game **The Lord of the Rings: The Return of the King** appears with a save file of ~9.5 GB of data. When I checked what kind of files it could have stored from a game I don't own nor have installed I saw that the entire Documents folder was copied into it.

![image](https://user-images.githubusercontent.com/44416875/175330619-f2eda737-4002-4025-aa25-b479bb3841ab.png)

Ludusavi app shows the same.

![image](https://user-images.githubusercontent.com/44416875/175335760-55e534b6-cc4f-46c1-9ee1-3ee23ace79c5.png)

I was wondering if I could exclude this game from being stored.

Thanks a lot.

**Comment by mtkennerly** [comment]
Thanks for reporting this! There was an error in the manifest updater script. I've fixed it and updated the manifest (https://github.com/mtkennerly/ludusavi-manifest/commit/2ae7df680bde9b55002bff30b258bf806c5f2f43), so this will be resolved the next time you launch Ludusavi.
