### ISSUE TITLE
Ludusavi Plugin not Finding Saves for Deathloop (Epic Store)

### ISSUE THREAD

**Issue by imfm** [mtkennerly/ludusavi-playnite#37]
The application finds the saves for Deathloop (Epic Store) and can back them up, but for some reason the plugin in Playnite does not detect them. "No save data found to back up for DEATHLOOP."

Save and config files detected here in the executable:
<home>/Saved Games/Arkane Studios/Deathloop/base/savegame/<storeUserId>
<home>/Saved Games/Arkane Studios/Deathloop/base

**Comment by imfm** [comment]
Looking at this issue:
https://github.com/mtkennerly/ludusavi-playnite/issues/15

I found the problem. Deathloop shows in Playnite as and in the Epic Launcher as DEATHLOOP, but in Ludusavi as Deathloop. Adding a capitalized custom entry fixes it.

Is there a way to make Ludusavi case insensitive to avoid this issue?

**Comment by mtkennerly** [comment]
Thank you! I'm really glad you like the project :)

> Is there a way to make Ludusavi case insensitive to avoid this issue?

Not currently, but I would want to add an option for that as part of https://github.com/mtkennerly/ludusavi/issues/86. I can't promise when that will be finished, but I recently caught up with my backlog of tickets from my other projects, so I'm hoping to start catching up on Ludusavi tickets soon 🤞
