### ISSUE TITLE
[Feature Request] Add option to run a script after save is backed up.

### ISSUE THREAD

**Issue by varoOP** [mtkennerly/ludusavi-playnite#38]
I wish to upload the folder to which ludosavi saves the backups, immediately after a new game savefile is backed up.
It will be easy to do so with a poweshell script, just need to ludosavi to trigger it after it creates a backup.

**Comment by mtkennerly** [comment]
This is something I'm planning to add to Ludusavi itself, rather than the Playnite plugin. You can track this ticket to see when it's completed: https://github.com/mtkennerly/ludusavi/issues/98
