### ISSUE TITLE
Notification not displaying when game save is not backed up on missing data

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#39]
Extension version: 0.10
Ludusavi version: 0.11 & 0.12.1

Game is Tinykin: https://www.pcgamingwiki.com/wiki/Tinykin

The save is not being backed up because the data is missing on PCGW but notificaitons are not being displayed.

Note: I've added the save location to the article after noticing this issue but the Ludusavi manifest should still be missing this info as the time of writing this

![image](https://user-images.githubusercontent.com/1389286/189474283-c09f5415-8397-4f99-add4-8670c4d5ddd4.png)

Extensions.log

```
10-09 02:28:56.178|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --merge --try-update --api --path "C:\Users\Brandon\MEGAsync\OneDrive\Backups\saves\PC" -- "Tinykin"
10-09 02:28:59.973|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content
```

I also tested after by trying to backup using this menu function

![image](https://user-images.githubusercontent.com/1389286/189474117-ea43d39c-8d0f-4c52-934d-07c29dede400.png)

```
10-09 02:33:38.910|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --merge --try-update --api --path "C:\Users\Brandon\MEGAsync\OneDrive\Backups\saves\PC" -- "Tinykin"
10-09 02:33:40.957|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content
```

https://user-images.githubusercontent.com/1389286/189474236-dfd1a6fa-cc68-47c6-aeae-f99f3a3f0fe6.mp4

**Comment by mtkennerly** [comment]
I can't reproduce this one either :/ I made a custom entry for a game to intentionally remove all paths, and I get the notification. I even uninstalled/reinstalled the extension from Playnite's plugin browser instead of using my local dev version, but it still worked. Has anything else changed in your environment recently?

> https://user-images.githubusercontent.com/4934192/189476079-d5356f6d-6375-48a7-99dc-02a60c8c6688.mp4

**Comment by darklinkpower** [comment]
I think that the only thing that has changed is that I'm using Playnite 10 but I think this issue has happened before that since I think it's been some time since I last saw this notification. I remember playing games that were recently released and never got a notification, which I found weird as I usually get them for those but never checked until now.

Here's a video of another game
- Ludusavi v0.12.1
- Ludusavi Playnite v0.10
- Game is "Kalinur", which doesn't even have an article on PCGW
- Log says `LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 0 and valid JSON content`


https://user-images.githubusercontent.com/1389286/189485075-bd58ad94-796f-4695-bc9c-67a030e2690d.mp4

**Comment by darklinkpower** [comment]
I just checked and disabling this option makes the notifications show

![image](https://user-images.githubusercontent.com/1389286/189486077-bc1b4496-f8a2-4d94-b078-1cd5462bdf9e.png)


https://user-images.githubusercontent.com/1389286/189486135-aab02cda-3d69-46a9-8094-a075306ee860.mp4

Is this by design? If that's the case, in my opinion the previous behavior would be better because it notified the user if a game save was not backed up so they could do add the data to PCGW/Ludusavi to fix this

**Comment by mtkennerly** [comment]
Ah, looks like I made a bad copy/paste that's causing several errors to be logged as info 😅 I'll fix this ASAP.
