### ISSUE TITLE
Add configuration for zipping

### ISSUE THREAD

**Issue by Maingron** [mtkennerly/ludusavi-playnite#41]
Maybe add the option to save and load backups as zip archive to decrease clutter and save space.
I'm not really into Ludusavi, but in Ludusavi itself you can enable zipping, if that helps any.

**Comment by Maingron** [comment]
Actually I did get a zip file after setting it up in Ludusavi itself, apologies for that. Maybe you can still add an option for zipping to the Playnite Extension, so it's all in one place.

**Comment by mtkennerly** [comment]
Yeah, backup format and retention are probably popular enough to justify including in the plugin directly.

**Comment by Maingron** [comment]
Wow, respect! Didn't expect this to get implemented nor released within less than a day. Good job!
