### ISSUE TITLE
Only 1 backup is created per game

### ISSUE THREAD

**Issue by Maingron** [mtkennerly/ludusavi-playnite#43]
Apparently, the max-backups per game settings don't work. No matter in which folder I look, I find only 1 backup and the mapping.yaml.
I activated the zip compression and changed the default path. Settings see screenshot.

In fact I now fiddled around a bit and the backup process seems bugged somehow. Not sure about the details.

![image](https://user-images.githubusercontent.com/47825439/201476594-f2afd2f7-53a1-44c6-9376-b16df8054ba3.png)

**Comment by mtkennerly** [comment]
Hi! Could you tell me which version of Ludusavi you're using? That particular setting requires Ludusavi 0.14.0 or newer.

Also, it will only create additional backups if the data for the game has changed, so make sure you're updating your save between tests.

When you say the backup seems bugged, what other specific issues are you seeing?

**Comment by Maingron** [comment]
I was using Ludusavi-Playnite v0.11.0 and Ludusavi v0.13.1. Didn't expect Ludusavi getting an update. Maybe you can implement a version check with a warning. 
Didn't get around to test extensively, but I'm having 2 backups in one folder now.

Regarding the bugginess: Backups sometimes only got deleted, so I either had 0 or 1 backup per game.

Running `ludusavi --version` in the terminal returns the version, if that's of any help.
![image](https://user-images.githubusercontent.com/47825439/201998853-ad0852b6-07b3-4070-91f9-d20b9b0a5a92.png)

Also sorry for the late response.

**Comment by mtkennerly** [comment]
There's actually a notification in Playnite for that :) It only triggers once per recommended update, though.

> <img width="185" alt="image" src="https://user-images.githubusercontent.com/4934192/202047113-52feaddd-bb6a-4c2c-9e95-af2216fe18b5.png">

Please let me know if you see that issue anymore with the latest version. For the games with 0 backups, do they have a mapping.yaml file? If so, would you mind uploading one of them here?

**Comment by Maingron** [comment]
Just going through all folders I can find, and, at least for Cities Skylines, which seems to be the only one remaining, there's no files at all, so no mapping.yaml.  
However, it's version related. Just didn't see the notification, I guess.  
Would a mapping.yaml from a working game help?

**Comment by Maingron** [comment]
Just going through all folders I can find, and, at least for Cities Skylines, which seems to be the only one remaining, there's no files at all, so no mapping.yaml.  
However, it's version related. Just didn't see the notification, I guess.  
Would a mapping.yaml from a working game help?

**Comment by mtkennerly** [comment]
If you delete the empty folder for Cities Skylines and back it up again, what happens? If it shows up empty again, then we can get some logs to narrow down the issue. If it ends up with save files, then I think we can consider this fixed :)

> Would a mapping.yaml from a working game help?

Nah, that wouldn't narrow it down.

**Comment by mtkennerly** [comment]
I'm going to close this for now, but let me know if anything changes or if the issue still occurs for new backups of Cities: Skylines.
