### ISSUE TITLE
Add a way to choose a game if it's not found in manifest

### ISSUE THREAD

**Issue by Destroy666x** [mtkennerly/ludusavi-playnite#46]
### What's your idea?

Would be nice to have a choice box/popup similar to HowLongToBeat's where it shows you the search phrase (which you can change and search again) and games that match it displayed in case a game can't be found.

Example of why it's needed: Heroes & Generals is called Heroes & Generals WWII on Epic Games. It's also probably solvable with Epic IDs in manifest (I saw there are GOG/Steam IDs) or something like that but this would solve nearly all kinds of different cases.

**Comment by mtkennerly** [comment]
Thanks for the suggestion! The search part will require a Ludusavi update, but in the meantime, this is how it will look:

## Context menu before/after assigning a name
> <img width="365" alt="image" src="https://user-images.githubusercontent.com/4934192/221632401-92e35e20-9b44-4af6-9f10-c3db3c6a4070.png">

> <img width="379" alt="image" src="https://user-images.githubusercontent.com/4934192/221632922-a45653fa-874e-4dab-a089-b6dff539a1c4.png">

## Name entry (with Ludusavi versions older than 0.16.0)
> <img width="324" alt="image" src="https://user-images.githubusercontent.com/4934192/221632722-9decf40e-fc20-4485-9e64-906e8a15b18c.png">

## Name entry (with Ludusavi 0.16.0+, when it's released)
I'm adding the plugin functionality in advance, so once Ludusavi 0.16.0 is out and installed on your system, the plugin will automatically support this:

> <img width="600" alt="image" src="https://user-images.githubusercontent.com/4934192/221632516-eb7f8717-ec40-4dd8-8c97-cca810c5b87a.png">

**Comment by Destroy666x** [comment]
Thanks, looking good!
