### ISSUE TITLE
Add a setting for automatically assigning the backup tag

### ISSUE THREAD

**Issue by Destroy666x** [mtkennerly/ludusavi-playnite#47]
A rather simple QoL change - add a checkbox setting like `Automatically assign "[Ludusavi] Game: backup" tag if backup succeeds` that when enabled adds the tag more or less when the success notification happens after all manual and automatic backup actions.

Another checkbox could also exist to `Automatically assign "[Ludusavi] Game: backup and restore" if backup succeeds` as an alternative

**Comment by mtkennerly** [comment]
Hi! Could you explain a bit more about the use case for this? I feel like the current options cover the same needs:

* If you've configured the plugin to ask before each backup, then you can choose "yes, always" to add the tag for the game in question.
* If you've configured the plugin to back up automatically (without asking) after playing a game, then there's no need to add the tag.
* If you want to add the tag to several games at once, you can shift+click and do it in bulk.

**Comment by Destroy666x** [comment]
The use case is that when you manually select games and select the backup option through RMB menu then the tag isn't added, unless I'm missing something. And why would I like to have the tag added when I do it manually? To quickly filter and select all the games I backed up in case a quick cloud backup is needed before e.g. moving temporarily or permamently between devices.

**Comment by mtkennerly** [comment]
> I don't want automated backups after playing

If you add the "[Ludusavi] Game: backup" tag to a game, then it will automatically be backed up after playing, so you probably don't want to use that tag for this. Even if it's disabled in the plugin settings, that tag will override the behavior per game.

There could be a new tag just to mark games that have been backed up. For now, you can use a custom tag for that so it doesn't trigger any special behavior.

**Comment by Destroy666x** [comment]
Oh, I see, thanks for info. A different predefined or choosable/enterable tag would be nice in that case.

**Comment by mtkennerly** [comment]
This will be included in the next release:

> <img width="335" alt="image" src="https://user-images.githubusercontent.com/4934192/221573550-7f3cbd04-d179-4eda-bb90-afe6fc1a8114.png">

It also takes the configured backup folder into account. If you change the folder, then it will update the tags to reflect what's in that folder.
