### ISSUE TITLE
Play action to "Restore" / "Backup"

### ISSUE THREAD

**Issue by jamie9090** [mtkennerly/ludusavi-playnite#49]
Would be great to be able to have a Play action to "Restore" or "backup" save games so it can be done via Playnite Fullscreen mode :)

**Comment by mtkennerly** [comment]
Hi! I asked on the Playnite Discord server, and it sounds like the context menu items from desktop mode should be available in full screen mode as well starting in Playnite 11. I think it'll be best to wait for that to release.
