### ISSUE TITLE
"requiring matching custom entry" and not backing up automatically?

### ISSUE THREAD

**Issue by Auncaughbove17** [mtkennerly/ludusavi-playnite#50]
Hi-Fi Rush detected in Ludusavi, but not automatically backing up after play. When manually clicking backup it shows this message, which makes no sense to me, am I doing something wrong?:
![image](https://user-images.githubusercontent.com/26165288/223841984-ee99377a-ae81-410c-ba5e-9cf2f5af82e1.png)

![image](https://user-images.githubusercontent.com/26165288/223841711-fd83347c-c600-4949-9123-a39c2aa1f810.png)

**Comment by mtkennerly** [comment]
That means the game doesn't have a PC platform set in Playnite. If you open the game details in Playnite, what does the platform field say?

(Ideally, it shouldn't use the platform to determine if it needs a custom entry. I should be able to improve that in the near future.)

**Comment by Auncaughbove17** [comment]
This is what it says:
<details><summary>Hi-Fi Rush</summary>

![image](https://user-images.githubusercontent.com/26165288/224083178-bc2e24f0-788c-4ece-b06a-9880475ade84.png)
</details>


For comparison here is Isaac, which also doesn't work:
<details><summary>Isaac</summary>

![image](https://user-images.githubusercontent.com/26165288/224083301-cbc88dfe-d893-498d-b4fb-bef947779592.png)
</details>

Interestingly, I have a custom entry for Forza Horizon 5 which DOES work, and it has no platform at all
<details><summary>Forza</summary>

![image](https://user-images.githubusercontent.com/26165288/224084656-1165ee74-a5a7-4162-b92b-acadd68a2396.png)
</details>

What seems to fix the issue is either removing all platforms that aren't `PC (Windows)` or just leaving the Platform blank. I made these like so:
1. starting, then directly stopping the games.
2. opening notification bar
3. opening game info
4. make screenshot

<details><summary>Screenshots with Platform changes</summary>

![image](https://user-images.githubusercontent.com/26165288/224085587-42435649-ee23-4333-b2a0-164e71404cfc.png)
![image](https://user-images.githubusercontent.com/26165288/224085893-ae7ed656-fa28-45d8-83ce-eec8a5aa13d1.png)
</details>

**Comment by mtkennerly** [comment]
> removing all platforms that aren't `PC (Windows)`

Yeah, that's definitely a bug. The plugin only checks the *first* platform, when it should check all of them. I'll fix that.

In the meantime, you can add the `[Ludusavi] Game: backup` tag to those games to force the automatic backups.

> wouldn't it make more sense to check the ludusavi manifest, if it has any entries?

Absolutely. The issue is that Ludusavi didn't have a way to export the manifest plus any custom games. The next release of Ludusavi will provide that functionality, and then the plugin can make use of it.

**Comment by Auncaughbove17** [comment]
> In the meantime, you can add the `[Ludusavi] Game: backup` tag to those games to force the automatic backups.

The weird thing is, that I did that. I even added the Platform Backup tag after it didn't work just to see if that would help.
<details><summary>image</summary>

![image](https://user-images.githubusercontent.com/26165288/224278071-fda3c0b3-5910-4481-8398-5ab5d83e7eb5.png)
</details>


Here is a video demonstrating that the tag doesn't seem to apply.

https://youtu.be/_--H9FNxLz4

**Comment by mtkennerly** [comment]
Thanks, that's very helpful. I think I see where the bad platform logic is even stopping it from checking the tags.

**Comment by mtkennerly** [comment]
I just published [v0.12.1](https://github.com/mtkennerly/ludusavi-playnite/releases/tag/v0.12.1), which fixes this.
