### ISSUE TITLE
Playne can't be backedup

### ISSUE THREAD

**Issue by Nightchanger** [mtkennerly/ludusavi-playnite#52]
![image](https://user-images.githubusercontent.com/45158783/230990874-e483b017-7316-4365-8d05-ee049cdd1638.png)

**Comment by mtkennerly** [comment]
Ludusavi gets the save lists [from PCGamingWiki](https://www.pcgamingwiki.com/wiki/Playne#Game_data), but the article for Playne didn't have any info on what to back up.

I found [this thread](https://steamcommunity.com/app/865540/discussions/0/1735462352458208717/) that answers where the saves are, so I've [added it to PCGamingWiki](https://www.pcgamingwiki.com/w/index.php?title=Playne&diff=1403838&oldid=1361751). It will be added into Ludusavi's data set automatically within a few hours :)
