### ISSUE TITLE
Automatic Cloud Backup doesn't warn when out of sync

### ISSUE THREAD

**Issue by Alistair1231** [mtkennerly/ludusavi-playnite#56]
Hi!
At first I thought it was broken, since it would make automatic local backups but not sync with rclone.
When I tried to make a backup manually instead of with playnite, it told me that it was out of sync and I should manually sync in the settings before trying again. After manually syncing the cloud it works now. I think the addon should warn the user about that.

**Comment by mtkennerly** [comment]
Hi! Yes, the plugin still needs an update to integrate alerts for cloud status. I'll try to get to this soon :)
