### ISSUE TITLE
Ludusavi manifest doesn't update if you don't use Ludosavi standalone

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#6]
I just noticed that even if the Ludusavi Manifest is updated, you won't get the new definitions if you only use the Playnite plugin. You need to open Ludusavi standalone. Ideally it should be downloaded automatically in Playnite by the plugin, although if not possible, maybe just giving the user a notice that there's a new version to be downloaded and that the program needs to be opened would work.

**Comment by mtkennerly** [comment]
Good catch! The plugin just needs to pass `--update` when doing a backup (and, if it fails because of no Internet connection, then retry without the flag). I could make updating opt-in from the extension menu, but I bet no one would remember to do it 🙃
