### ISSUE TITLE
Option to exclude Configuration files

### ISSUE THREAD

**Issue by designgears** [mtkennerly/ludusavi-playnite#62]
I switch between my main pc and my handheld device a lot. The handheld is a much different configuration, it would be nice to have an option to ignore config files within the plugin.

**Comment by mtkennerly** [comment]
Thanks for the suggestion! There's a similar ticket in the Ludusavi repository: https://github.com/mtkennerly/ludusavi/issues/218 . You can follow that one for any updates on this feature in the future.
