### ISSUE TITLE
Unable to run ludusavi error on Playnite 10.32

### ISSUE THREAD

**Issue by Darkcitrus** [mtkennerly/ludusavi-playnite#67]
Playnite, ludusavi, and the plugin are all the latest version & ludusavi runs standalone just fine, but playnite can no longer backup any saves with it, always giving the same error of unable to run ludsavi. 
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/141195541/293f1f50-92f0-4d37-af57-61fff1eddb88)

![image](https://github.com/mtkennerly/ludusavi-playnite/assets/141195541/422280e2-32e3-49a0-a25d-eaff8b3b3237)

![image](https://github.com/mtkennerly/ludusavi-playnite/assets/141195541/d1cb2812-a453-4469-bc45-58015624faf7)

**Comment by mtkennerly** [comment]
Hi! I'm not able to reproduce this. Could you upload a copy of your `extensions.log` from Playnite?

**Comment by Darkcitrus** [comment]
[extensions.log](https://github.com/mtkennerly/ludusavi-playnite/files/13798277/extensions.log)
[extensions.00000.log](https://github.com/mtkennerly/ludusavi-playnite/files/13798278/extensions.00000.log)
I found two of them. 
in extensions.00000.log I found some related entries to ludusavi, here you go:
```07-11 20:19:28.205|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: backup --force --merge --try-update --api
07-11 20:19:28.205|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi could not be executed
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at LudusaviPlaynite.LudusaviPlaynite.RunCommand(String command, String args)
   at LudusaviPlaynite.LudusaviPlaynite.InvokeLudusaviDirect(Invocation invocation, Boolean standalone)
07-11 20:19:28.205|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with -1 and invalid JSON content
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at LudusaviPlaynite.LudusaviPlaynite.InvokeLudusavi(Invocation invocation)

**Comment by mtkennerly** [comment]
Could you try opening Command Prompt and running these commands?

```
set RUST_BACKTRACE=1
C:\Games\ludusavi.exe --try-manifest-update find --api --backup -- "Baldur's Gate III"
```

That's the last command that failed in extensions.log:

```
30-12 16:12:56.526|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Running Ludusavi: --try-manifest-update find --api --backup -- "Baldur's Gate III"
30-12 16:12:58.985|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Ludusavi exited with 101 and invalid JSON content
```

**Comment by Darkcitrus** [comment]
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/141195541/2e5efef3-a6b6-4e6b-9d49-095cdbbbdf57)
Here's what came up.

**Comment by Darkcitrus** [comment]
```Microsoft Windows [Version 10.0.19045.3803]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Dark>set RUST_BACKTRACE=1

C:\Users\Dark>C:\Games\ludusavi.exe --try-manifest-update find --api --backup -- "Baldur's Gate III"
thread 'main' panicked at src\scan\layout.rs:442:44:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

C:\Users\Dark>
C:\Users\Dark>set RUST_BACKTRACE=1

C:\Users\Dark>C:\Games\ludusavi.exe --try-manifest-update find --api --backup -- "Baldur's Gate III"set RUST_BACKTRACE=1
thread 'main' panicked at src\scan\layout.rs:442:44:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

C:\Users\Dark>C:\Games\ludusavi.exe --try-manifest-update find --api --backup -- "Baldur's Gate III"

**Comment by Darkcitrus** [comment]
After a few tries, nothing comes up anymore. 
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/141195541/996e556e-b60a-418e-a3a1-e59492fe9226)

**Comment by mtkennerly** [comment]
Thanks, that narrows it down. Somehow, one of the `mapping.yaml` files from your backups got into an invalid state, but I'm not sure how that could be. Do you have any other scripts/plugins that might have modified the backup folder?

Since it suddenly started working, it seems that the file either disappeared or got fixed, so you should be okay for now, but let me know if you still have any issues in Playnite.

I'll definitely update Ludusavi so that this kind of error doesn't make the whole program crash. I'm just not sure how the issue appeared in the first place.

**Comment by Darkcitrus** [comment]
Well, it still doesn't work on my end even if if the cmd does, I still get the same errors in Playnite regardless of which game I'm trying to backup. 

If it's any hint to how this happened, I think it started happening around the same time I re-attached several storage drives that weren't in use prior to installing ludusavi/playnite, one of which had an older version of ludusavi on it (without playnite).

**Comment by Darkcitrus** [comment]
Update, your hint about `mapping.yaml` got me to figure out that changing the directory in which saves are stored (from C:\Users\Dark\ludusavi-backup to C:\Users\Dark\ludusavi-playnite) seems to fix it fully for me, now backing up works via Playnite just fine!

I'm not sure if I should close the issue since my problem was resolved or leave it open since the root of it is still to be fixed though! 

I'll leave it open for you to do with it as you see fit, thank you for helping out with this. :)

**Comment by mtkennerly** [comment]
Glad you found a solution that works for you :)

If you'd still like to troubleshoot your original backups and get them working, then you can try this build with a fix for the "did not contain valid UTF-8" crash:

[ludusavi-v0.22.0-post.6+4489f49-win64.zip](https://github.com/mtkennerly/ludusavi-playnite/files/13848897/ludusavi-v0.22.0-post.6%2B4489f49-win64.zip)

If you still see issues in Playnite with that build, then I'd like to see the updated `extension.log` from Playnite and a copy of `%APPDATA%\ludusavi\ludusavi_rCURRENT.log` (if it exists).

**Comment by Darkcitrus** [comment]
Sure, I'll try it out and set the old backups! Will update when I do.

**Comment by Darkcitrus** [comment]
Update, the new build works with the old backups, so all is well!

**Comment by mtkennerly** [comment]
Great! Thanks for confirming.

If you're curious which specific backup is corrupted, then `%APPDATA%\ludusavi\ludusavi_rCURRENT.log` should have a line like `Ignoring unloadable mapping:` with the path to the relevant game. I can try to help salvage it if you send me the game backup folder, or if you're not too worried about it, then you could just delete the folder for that game's backups.

**Comment by Darkcitrus** [comment]
Ah, it was a random save game for Metro 2033, that's totally fine with me to get rid of but thank you for the offer! Your software is the best at keeping backups of my saves really. :)
