### ISSUE TITLE
add open folder

### ISSUE THREAD

**Issue by Lacro59** [mtkennerly/ludusavi-playnite#7]
It's possible to add (in settings menu for example) a button to open the folder contains the back up?

**Comment by mtkennerly** [comment]
I actually tried to do this originally, but I had some trouble getting it to work right 😅 But yes, it would be a good addition.

**Comment by mtkennerly** [comment]
![image](https://user-images.githubusercontent.com/4934192/89154811-a0718a80-d535-11ea-9285-a0cea0f87acd.png)
