### ISSUE TITLE
Change backed up saves order in context menu to descending

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#70]
Currently they are ordered in ascending order, from oldest to newest.
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/1389286/17f9c078-3622-4e33-9f3f-a1b9551af990)

May I suggested if the order could be changed to descending, meaning, from newest to oldest from top to bottom? I think it would make more sense that way to have listed the most recent one first.

**Comment by mtkennerly** [comment]
Makes sense to me :+1:
