### ISSUE TITLE
Having issues with launching it? (see screenshots)

### ISSUE THREAD

**Issue by MapleEmbers** [mtkennerly/ludusavi-playnite#72]
Having issues with launching it? (see screenshots)

I am able to launch it fine manually but the button in Playnite throws this error

![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/696ce34f-96f0-4935-a514-817ee5e704d0)
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/ea26b21c-d196-472c-a4f1-396391a2fdd4)
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/65a790f8-f52f-4d46-a980-ecd064eb6806)

**Comment by MapleEmbers** [comment]
Just to clarify, the appdata folder is correct:
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/538d5a17-552d-4722-98b4-b22d1577e4cd)

**Comment by mtkennerly** [comment]
Hmm, in your screenshot of the Playnite folder, most of the files have extensions, but `ludusavi` doesn't. Is it just named `ludusavi` and not `ludusavi.exe`?

**Comment by MapleEmbers** [comment]
I have windows hiding extensions of knows file types, as you can see with `license.txt` showing as just `license`, it is in fact `ludusavi.exe`

**Comment by mtkennerly** [comment]
That's very strange. Could you please try with this build? It just adds an extra log message:

[ludusavi-playnite-v0.14.0-issue-72-v1.zip](https://github.com/mtkennerly/ludusavi-playnite/files/15440168/ludusavi-playnite-v0.14.0-issue-72-v1.zip)

After installing it, try to use the launch option again, and then check `%APPDATA%\Roaming\Playnite\extensions.log` for a line like this and copy/paste it here:

```
24-05 17:23:38.299|DEBUG|LudusaviPlaynite#LudusaviPlaynite:Launching Ludusavi: 'C:\git\ludusavi\target\debug\ludusavi.exe', exists: True, siblings: C:\git\ludusavi\target\debug\.cargo-lock|C:\git\ludusavi\target\debug\ludusavi.d|C:\git\ludusavi\target\debug\ludusavi.exe|C:\git\ludusavi\target\debug\ludusavi.pdb
```

**Comment by MapleEmbers** [comment]
Hey, sorry your reply got lost in my notifications when it was flooded .-. I tried that and got this: https://pastebin.com/17RC8TE4

Thats the full log with the 0.14.0 that you sent in your last message, I also tried the v0.15.0 to the same result. I could not see a line like that in the log so i just sent the whole log from boot to after it threw the error message

**Comment by mtkennerly** [comment]
No worries about the delay!

That's strange that the log line doesn't appear. Just to confirm, did you try using the `Ludusavi > Launch` option to trigger the error first before copying the log file?

**Comment by MapleEmbers** [comment]
I tried both `Tools> Ludu Savi` and the quick launch button on the left bar

**Comment by mtkennerly** [comment]
Hmm, this extension doesn't add a quick launch button on the left.

* Did you add that manually or via another extension?
* Would you mind sharing a screenshot of the two launch options you used?
* What other extensions do you have installed?

Just to make sure we're talking about the same thing, I'm referring to this launch option:

> ![image](https://github.com/mtkennerly/ludusavi-playnite/assets/4934192/0ed45df6-dceb-4021-be5b-3052334abc61)

**Comment by MapleEmbers** [comment]
as for addons:
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/654b9bca-7366-4373-98b8-470fed96364a)
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/6fc83bc4-9acf-4ed0-8ac7-dd2737871ec2)
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/41f7b418-7926-4e84-a610-ac6231778bbb)

**Comment by mtkennerly** [comment]
Ah, okay, I wasn't aware of Playnite's "software tools" feature, but that's where this is coming from.

In Playnite, go to `Library > Software Tools...`, find the entry for Ludusavi, and update the path to match your executable's location. This extension doesn't configure anything in the software tools list, so that's out of my control 😅

**Comment by MapleEmbers** [comment]
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/138142803/0db419f1-a1f6-4e3f-bf7a-3e02149649ef)
ah yes, thats the wrong path

**Comment by MapleEmbers** [comment]
yup, that fixed both of the buttons i used, thanks ^^
