### ISSUE TITLE
Backup across multiple devices

### ISSUE THREAD

**Issue by TotesFab** [mtkennerly/ludusavi-playnite#74]
Hi,

I use Ludasavi with GDrive.  My saves are backed up to Google on both my desktop and laptop, but I don't use the same Windows account name for both.  When I try to restore a game from Desktop to my Laptop, ludusavi extension doesn't see it. My assumption is because games saves in My Documents are using different paths like "C:/Users/TotesFab/My Documents/" and "C:/Users/TotallyFab/My Documents"

Is there a way to make this use case work?  Currently I am trying to play the GOG version of Battle Brothers so I can't use steam cloud saves.

-Edit- I know I can just copy and paste the files into the proper places, but I was hoping for an easier way

**Comment by mtkennerly** [comment]
Hi! You can do this by configuring redirects in Ludusavi.

For example, on the computer where you use TotesFab as your username, you could add this redirect:

> ![image](https://github.com/mtkennerly/ludusavi-playnite/assets/4934192/8e9695a0-d306-4c7d-a58a-3e899553cfdb)

This says: "Whenever you're about to restore a file to `C:/Users/TotallyFab`, actually restore it to `C:/Users/TotesFab` instead".

**Comment by TotesFab** [comment]
Thank you!  I will try this out.  I didn't if this was a ludusavi thing or the playnite extension and was nervous.  I appreciate you helping me out regardless.

**Comment by mtkennerly** [comment]
No worries! I maintain both projects, so I'll see it either way 🙃 

I'll close this for now, but feel free to respond here if you run into any issues or have further questions.

**Comment by TotesFab** [comment]
So I just wanted to update the ticket for those who see this in the future, lol.

I actually was using the same Windows Account for both machines so something else was wrong.  I forgot to go into the Restore tab of Ludusavi and tell it to restore from Gdrive.  Now it works.
