### ISSUE TITLE
Open Backup directory menu item is not available when multiple items are selected

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#78]
I don't know if it's intended or due to a limitation. If it's the former, in my opinion there's no harm in also supporting multiple games and just open the backup directories of all them when used since it could be useful in some scenarios.

Single game (Available):
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/1389286/823a1cb0-e730-476e-8311-4db390451ccd)

Multiple games (Missing):
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/1389286/9b22a33e-bdf5-4931-8a17-ee0089602a64)

**Comment by mtkennerly** [comment]
Yeah, that's fair. I was thinking it might be confusing if only some of the selected games have a backup folder, but it's not a big deal to just open it for the games that do have one. I've changed it to show the option if at least one selected game has a backup.

By the way, thanks for always sharing your ideas for improvements :)
