### ISSUE TITLE
Backing up saves in game menu doesn't refresh backups to restore

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi-playnite#79]
![image](https://github.com/mtkennerly/ludusavi-playnite/assets/1389286/260c1bfe-5469-425a-a6e6-880e0683835f)

Here's a video displaying the issue:

https://github.com/mtkennerly/ludusavi-playnite/assets/1389286/c80a6551-0be5-4398-b1d1-8548362162f1

**Comment by mtkennerly** [comment]
Hi! I can't seem to reproduce this. Would you mind sending me your `extensions.log` from when it happens? And does it make any difference if you wait a bit longer before opening the context menu?

**Comment by darklinkpower** [comment]
> And does it make any difference if you wait a bit longer before opening the context menu?

I'm sorry, this was the issue. Waiting a little more time properly updated the available backups, my bad 😣

**Comment by mtkennerly** [comment]
No worries :)
