### ISSUE TITLE
save after game session

### ISSUE THREAD

**Issue by Lacro59** [mtkennerly/ludusavi-playnite#8]
It's possible to add a option for activate (or no) a back up after a game session?

**Comment by mtkennerly** [comment]
The plugin already does this, unless I'm misunderstanding your request? By default, you should see a dialog like this when you exit a game. Is it not happening for you?

![image](https://user-images.githubusercontent.com/4934192/89100339-47361980-d3c4-11ea-982d-5354702299cf.png)

**Comment by Lacro59** [comment]
My request is to add a option for activate this or not.
And to have the possibility that the action is automatic without dialogue confirmation.

**Comment by mtkennerly** [comment]
I see, there are already some checkboxes for that actually. Disabling "but ask first" will make it automatic without asking, and disabling "back up save data when you finish playing" will turn off the feature altogether.

![image](https://user-images.githubusercontent.com/4934192/89101038-6cc62180-d3ca-11ea-9131-3a360d741214.png)

**Comment by Lacro59** [comment]
Ok. Thanks. I go to sleep...
