### ISSUE TITLE
Add a blacklist option to ignore some games

### ISSUE THREAD

**Issue by Shifk97** [mtkennerly/ludusavi-playnite#9]
Would be a great option because some don't require to be saved (online games, for example)

**Comment by mtkennerly** [comment]
Good idea! I'll look into this.

**Comment by Shifk97** [comment]
Thanks ! and tyvm for your work, it is a great app.

**Comment by N0tJust1n** [comment]
An easy implementation of this might be to ignore any games with a specific tag and then let us tag any game with a phrase like "nobackup".

**Comment by mtkennerly** [comment]
This is now available in [v0.3.0](https://github.com/mtkennerly/ludusavi-playnite/releases/tag/v0.3.0) by creating a `ludusavi-skip` tag.

@N0tJust1n Good call on the tag suggestion \:D Much better than what I was originally imagining.

**Comment by jerrygreen** [comment]
Didn't know this plugin had such an option.

For better UX, please add a tick like this:

> - [ ] Remember my choice

To dialog window like this:

![image](https://user-images.githubusercontent.com/13215662/156872815-25ce8652-0ccf-4888-9966-304bba0d98df.png)

**Comment by mtkennerly** [comment]
@jerrygreen Thanks for the suggestion! I've made a separate ticket to track that idea: https://github.com/mtkennerly/ludusavi-playnite/issues/31
